# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - 5432:5432
  bot:
    build: .
    depends_on:
      - db
    volumes:
      -  .:/usr/src/app
    env_file:
      - .env
